before_install:
# Below is a fix to for `package requires NuGet client version '3.0' or above, but the current NuGet version is '2.12.0.0'.`
# according to https://github.com/travis-ci/travis-ci/issues/5932
# We skip downloading and restoring latest nuget.exe as we have it in our solution
# - mkdir -p .nuget
# - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
#- cd $TRAVIS_BUILD_DIR
- mono .nuget/nuget.exe
install:
- mono .nuget/nuget.exe restore Bridge.NoTest.sln -Verbosity detailed
env:
  global:
  - secure: h8UC6JsnMa9bwGP7/efFsJUVwmz8OqUZy37LIL/J5rkjHtzzEexRDi4gSEOkp3EgqNOupDd7PpWBJGkDhr/5sSB+3NkEh/4DeHNdHWYWEZzpmTZQuRggk8RSNohw8TIXOLh4wqm0PIEIKzBjYYInJvU9rWVHvdD7QvJu6nYOwNxKtnXTGhEeWma5fFA3Kge/aIMyMB5pxEoT6NjWBwwEzb6OZEi6bgbIQk6SMvGe/UcZ4X0oYcjKaUuR2hHfZnAkeUkFFqmo+yJl2PihJVggmnpwRA/RYyg0Amg+AbF1/LvlBtAau6e75+O284a2TNY3kHjq6E6dB0ZHjwFGmWHaVb773c4DZCvZpxZinTXSM5MAa2UG/BDYI7vmyyLaHkIcyghve3Jm2ub1+UPqkVymbUtOGfvl80B8KCRxaMPLTDwajY3piIPnUY41y6hoYqP94P6N6XxExcj/2kjl2cg0JCFEZrG/HBf28gFgzlTL2HidanAQdh/ns7uWv+o3LqsI/TF+JD/Una4juNiT7I1vHEmHfVH6TEDXauf7bisO5p7jcX+yWllWIRu7kKlT7afHaQzk8GlXu7glKoMyGGwJ71exPvRUqACRe+gCDT7I6/AbM4ozxHj5AGLzoQVE8wZViFaLRv1h6kTFSx3jtlKKM6DsdHq6yyG5FusQbs9P3kE=
  - secure: j3IhmT3tW1GqNVY8UuZK/1O4RbVI6Me++vSSkOcR6aJTTTWPoLmWX440ZVDwdeiWJor4Rx/gAVfE2K1ZSegRvcPe0eyKV6/P1cDpss28LXUN/rqDDWizzF/Oq8su/vCV7ZC9AXqXLBK+Z0EqCq/N2CQbFORxyvV/xd2KkCe3IhkEVaCz/1uzfJfTg4IWkBBqxhyFWvgXAi8MCvSjf/QqagF2GW3D3pL39pIKMCEP2OXaOWKfX/2EpkPXm2GB1OEM+ZmN67s1D8dhCEUyFk4B9qtGcz3cSPnTqjLte28jKVVUOWmsFsklvNf6htYlWI+oYo1Cvm6ODrvs9uywdmMEgEaiZGXDX1V3fiyR/lurx7t5cVcpHSWKzqOf4wJI6XPIKKiNpbBflhEnXbgyLgZBA6p3otsDXk1MmKp7rHoCIP2nLhqNQaPelC3JwyHgeiHIHQfTUCJGkXTgmfCmUSz1CJpDA9nBhzWBfWMSqUpJBKceU95PA5JMa3tYY35+r3nTNOPbSnNQQ2L3MD/gZelcZVkv/l46qLqV4InVjrUDE7+AlmhJCGvgvPp1J1Fh8i0zoXJH4O/QLI6Bk3nZbyeWlTy33fvsdFAP9xqUBt3svM5/JnDkvOMF11Mr0qOpcreb0UoiSO/JQAnaDdENTBV9M+gmADGPEIEeB63Z0/l2mgM=
language: csharp
solution: Bridge.NoTest.sln
before_script:
- npm install
- npm install -g grunt-cli
- git submodule update --init --recursive
script:
- xbuild /p:Configuration=Release Bridge.NoTest.sln
- mono ./packages/NUnit.ConsoleRunner.*/tools/nunit*-console.exe ./Compiler/TranslatorTests/bin/Release/Bridge.Translator.Tests.dll
- npm test
cache:
  directories:
  - packages
notifications:
  slack:
    secure: Gs/hlDNJYnOk35VqX/VNOKxvj8IyDG2R45rnqLaOb1DMa5DHRa7zkzi4fPCFenPYUFWWKPBfH9OmF75AESoqn9lCMIG2u7r2wTh25G2kBryDpXVd4r+XzWuAQYvJ48HHX7S2+yRVO96ZoPCf0ObFxG8Wq9nF80Hl+CiveKkAXcSznOrDqkCFAXXuq3919PTaxqWdvVSWTKhlD7i8PclBjKciow/O9ie6pwW+PzgNnrhQuHBqWJwauyAEhHZt/AyT1jrBweX9+IGjncE4S25qSQryLBbbCVdNQOZLdYFzn53OgtdSHsFfFYeZceH5epoGYJiMDxXUg+CrbmO5DUQa7HRAYwAMU7XmH1Xu8M+SUi1PctLgqXm0P7qZ5e+xYMQYZipX7xYykyWBPnpMahG9mA09UJ1ezVQHCAzV585qdZ/HZJxGK+3DUzIDpuXJiHpML7fkfx4GZzqTiYLctZEx8oZOsOErOFVJI08nlm3IFg3KTagrPUw5hFHJRWVF3IwhnZ/N28zEMufD+/cTCK6tXcu08KZgY3qGivgi4lHHkXEbkt/ubaH9Kf6GlNjvCDmMELpAm2pDf+3gJTF8MPWmNy6QfkZ2xK9qQWJjui+c8FZOypgEOCUw9ErzFCVxGjHgNwuXn5dcH8JJLYGUoVEf9XM/glyd2M5oxGjl+ITHEcQ=
